kernel:
  image: linuxkit/kernel:4.9.34
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:43c52456571369d62882605e4d510f0df3ed93de
  - linuxkit/runc:5f9941eed05f58293f928c9f2f0b6a3f9f6f55c1
  - linuxkit/containerd:b991571dd383351dbb2873f9ae3b70475adb6816
  - linuxkit/ca-certificates:4df823737c9bf6a9564b736f1a19fd25d60e909a
  - samoht/fdd
onboot:
  - name: sysctl
    image: linuxkit/sysctl:02d2bd74509fd063857ceb4c4f502f09ee4f2e0a
services:
  - name: getty
    image: linuxkit/getty:ebe3397aa9b08e8f310121fdb0aac9406e1c8e73
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:bdabfe138f05f7d48396d2f435af16f5a6ccaa45
  - name: dhcpcd
    image: linuxkit/dhcpcd:1033f340e2d42f86a60aab70752346f0045ea388
files:
  - path: etc/init.d/020-fdd-init
    mode: "0700"
    contents: |
      #!/bin/sh
      /bin/fdd init -vv -s /run/fdd.sock
  - path: etc/init.d/030-fdd-share
    mode: "0700"
    contents: |
      #!/bin/sh
      /bin/fdd share -vv -s /run/fdd.sock /tmp/channel-net-eng &&
      /bin/fdd share -vv -s /run/fdd.sock /tmp/channel-conf-net &&
      /bin/fdd share -vv -s /run/fdd.sock /tmp/channel-conf-act
trust:
  org:
    - linuxkit
