kernel:
  image: linuxkit/kernel:4.9.34
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:b7a8f94dfb72f738318cc25daf05451ed85ba194
  - linuxkit/runc:436357ce16dd663e24f595bcec26d5ae476c998e
  - linuxkit/containerd:d445de33c7f08470187b068d247b1c0dea240f0a
  - linuxkit/ca-certificates:4de36e93dc87f7ccebd20db616ed10d381911d32
  - samoht/fdd
onboot:
  - name: sysctl
    image: linuxkit/sysctl:a88a50c104d538b58da5e1441f6f0b4b738f76a6
services:
  - name: getty
    image: linuxkit/getty:06f34bce0facea79161566d67345c3ea49965437
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:310c16ec5315bd07d4b8f5332cfa7dc5cbc7d368
  - name: dhcpcd
    image: linuxkit/dhcpcd:2a8ed08fea442909ba10f950d458191ed3647115
files:
  - path: etc/init.d/020-fdd-init
    mode: "0700"
    contents: |
      #!/bin/sh
      /bin/fdd init -vv -s /run/fdd.sock
  - path: etc/init.d/030-fdd-share
    mode: "0700"
    contents: |
      #!/bin/sh
      /bin/fdd share -vv -s /run/fdd.sock /tmp/channel-net-eng &&
      /bin/fdd share -vv -s /run/fdd.sock /tmp/channel-conf-net &&
      /bin/fdd share -vv -s /run/fdd.sock /tmp/channel-conf-act
trust:
  org:
    - linuxkit
