kernel:
  image: "linuxkitprojects/kernel-memorizer:4.10_dbg"
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:6542ad0457ac153861870bfe2d036b6647cdc69f
  - linuxkit/runc:436357ce16dd663e24f595bcec26d5ae476c998e
  - linuxkit/containerd:eeb3aaf497c0b3f6c67f3a245d61ea5a568ca718
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:2a8ed08fea442909ba10f950d458191ed3647115
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:06f34bce0facea79161566d67345c3ea49965437
    env:
     - INSECURE=true
trust:
  org:
    - linuxkit
