kernel:
  image: linuxkit/kernel:5.10.47
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:eb597ef74d808b5320ad1060b1620a6ac31e7ced
  - linuxkit/runc:21dbbda709ae138de0af6b0c7e4ae49525db5e88
  - linuxkit/containerd:2f0907913dd54ab5186006034eb224a0da12443e
  - linuxkit/ca-certificates:c1c73ef590dffb6a0138cf758fe4a4305c9864f4
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:52d2c4df0311b182e99241cdc382ff726755c450
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:3c6e89681a988c3d4e2610fcd7aaaa0247ded3ec
    env:
     - INSECURE=true
  - name: influxdb
    image: influxdb:1.7
    net: host
    capabilities:
      - CAP_NET_BIND_SERVICE
      - CAP_DAC_OVERRIDE
  - name: kapacitor
    image: kapacitor:1.5
    net: host
    capabilities:
      - all
    env:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
  - name: telegraf
    image: telegraf:1.9
    net: host
    capabilities:
      - all
  - name: chronograf
    image: chronograf:1.7
    net: host
    capabilities:
      - CAP_NET_BIND_SERVICE
      - CAP_DAC_OVERRIDE
    env:
      - INFLUXDB_URL=http://127.0.0.1:8086
      - KAPACITOR_URL=http://127.0.0.1:9092
