# Simple example of using an external logging service
kernel:
  image: linuxkit/kernel:5.10.76
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:eb597ef74d808b5320ad1060b1620a6ac31e7ced
  - linuxkit/runc:9f7aad4eb5e4360cc9ed8778a5c501cce6e21601
  - linuxkit/containerd:2f0907913dd54ab5186006034eb224a0da12443e
  - linuxkit/ca-certificates:c1c73ef590dffb6a0138cf758fe4a4305c9864f4
  - linuxkit/memlogd:fe4a123b619a7dfffc2ba1297dd03b4ac90e3dd7
onboot:
  - name: sysctl
    image: linuxkit/sysctl:0dc8f792fc3a58afcebcb0fbe6b48de587265c17
  - name: dhcpcd
    image: linuxkit/dhcpcd:52d2c4df0311b182e99241cdc382ff726755c450
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
# Inside the getty type `/proc/1/root/usr/bin/logread -F` to follow the log
  - name: getty
    image: linuxkit/getty:3c6e89681a988c3d4e2610fcd7aaaa0247ded3ec
    env:
     - INSECURE=true
# A service which generates log messages for testing
  - name: write-to-the-logs
    image: alpine:3.13
    command: ["/bin/sh", "-c", "while /bin/true; do echo hello $(date); sleep 1; done" ]
  - name: write-and-rotate-logs
    image: linuxkit/logwrite:568325cf294338b37446943c2b86a8cd8dc703db
  - name: kmsg
    image: linuxkit/kmsg:2ed5334395ec64a7844a2cbd88837050fbd34880
