# Simple example of using an external logging service
kernel:
  image: linuxkit/kernel:5.10.47
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:78fb57c7da07c4e43c3a37b27755581da087a3b6
  - linuxkit/runc:5f9941eed05f58293f928c9f2f0b6a3f9f6f55c1
  - linuxkit/containerd:1c4d860d198095565baa3d8d60d434f034f0fef0
  - linuxkit/ca-certificates:4df823737c9bf6a9564b736f1a19fd25d60e909a
  - linuxkit/memlogd:9b0e8a5b3f67672234170d88833163caf7898984
onboot:
  - name: sysctl
    image: linuxkit/sysctl:02d2bd74509fd063857ceb4c4f502f09ee4f2e0a
  - name: dhcpcd
    image: linuxkit/dhcpcd:1033f340e2d42f86a60aab70752346f0045ea388
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
# Inside the getty type `/proc/1/root/usr/bin/logread -F` to follow the log
  - name: getty
    image: linuxkit/getty:ebe3397aa9b08e8f310121fdb0aac9406e1c8e73
    env:
     - INSECURE=true
# A service which generates log messages for testing
  - name: write-to-the-logs
    image: alpine:3.13
    command: ["/bin/sh", "-c", "while /bin/true; do echo hello $(date); sleep 1; done" ]
  - name: write-and-rotate-logs
    image: linuxkit/logwrite:e64e0f06e485e3542b58f3517da3bc13f246d208
  - name: kmsg
    image: linuxkit/kmsg:fa82d93cab0c1efa178cc51ffb82b83cc011148e
