kernel:
  image: linuxkit/kernel:5.10.76
  cmdline: "console=ttyS0"
init:
  - linuxkit/init:eb597ef74d808b5320ad1060b1620a6ac31e7ced
  - linuxkit/runc:9f7aad4eb5e4360cc9ed8778a5c501cce6e21601
  - linuxkit/containerd:2f0907913dd54ab5186006034eb224a0da12443e
  - linuxkit/ca-certificates:c1c73ef590dffb6a0138cf758fe4a4305c9864f4
onboot:
  - name: sysctl
    image: linuxkit/sysctl:0dc8f792fc3a58afcebcb0fbe6b48de587265c17
  - name: dhcpcd
    image: linuxkit/dhcpcd:52d2c4df0311b182e99241cdc382ff726755c450
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:84727a54a54e24099104849cb1e7fc5ef1ade7a2
    command: ["/usr/bin/metadata", "vultr"]
services:
  - name: getty
    image: linuxkit/getty:3c6e89681a988c3d4e2610fcd7aaaa0247ded3ec
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:a44c6230f1620f1d6310b95a9e9f585de73a8bd7
  - name: sshd
    image: linuxkit/sshd:4696ba61c3ec091328e1c14857d77e675802342f
    binds:
     - /run/config/ssh/authorized_keys:/root/.ssh/authorized_keys
  - name: nginx
    image: nginx:1.13.8-alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
