kernel:
  image: linuxkit/kernel:5.10.76
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:eb597ef74d808b5320ad1060b1620a6ac31e7ced
  - linuxkit/runc:21dbbda709ae138de0af6b0c7e4ae49525db5e88
  - linuxkit/containerd:2f0907913dd54ab5186006034eb224a0da12443e
  - linuxkit/ca-certificates:c1c73ef590dffb6a0138cf758fe4a4305c9864f4
onboot:
  - name: sysctl
    image: linuxkit/sysctl:0dc8f792fc3a58afcebcb0fbe6b48de587265c17
  - name: dhcpcd
    image: linuxkit/dhcpcd:52d2c4df0311b182e99241cdc382ff726755c450
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: format
    image: linuxkit/format:b2c5f160916ba4793fda7bdc9fe66c68df116a61
  - name: mount
    image: linuxkit/mount:43a2c1fb1ee19d0b2fe696655844cd6800e76aff
    command: ["/usr/bin/mountie", "/var/external"]
  - name: swap
    image: linuxkit/swap:77305236719ed7ab4be0f3bccc179c583fe7f5ff
    # to use unencrypted swap, use:
    # command: ["/swap.sh", "--path", "/var/external/swap", "--size", "1G"]
    command: ["/swap.sh", "--path", "/var/external/swap", "--size", "1G", "--encrypt"]
services:
  - name: getty
    image: linuxkit/getty:3c6e89681a988c3d4e2610fcd7aaaa0247ded3ec
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:a44c6230f1620f1d6310b95a9e9f585de73a8bd7
