# publish changes that are merged to master
name: Packages Push
on:
  workflow_run:
    workflows: [LinuxKit CI]
    types: [completed]
    branches: [master, main]

jobs:
  packages:
    name: Publish Changed Packages
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1
      with:
        path: ./src/github.com/linuxkit/linuxkit
    - name: Download linuxkit
      uses: actions/github-script@v3.1.0
      with:
        script: |
          var artifacts = await github.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{github.event.workflow_run.id }},
          });
          var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
            return artifact.name == "linuxkit-amd64-linux"
          })[0];
          var download = await github.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip',
          });
          var fs = require('fs');
          fs.writeFileSync('${{github.workspace}}/bin/linuxkit-amd64-linux.zip', Buffer.from(download.data));
    - run: cd bin && unzip linuxkit-amd64-linux.zip
    - name: Symlink Linuxkit
      run: |
        chmod ugo+x bin/linuxkit-amd64-linux
        sudo ln -s $(pwd)/bin/linuxkit-amd64-linux /usr/local/bin/linuxkit
        /usr/local/bin/linuxkit version
    - name: Restore Package Cache
      uses: actions/cache@v2
      with:
        path: ~/.linuxkit/cache/
        key: ${{ runner.os }}-linuxkit-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-linuxkit-
    - name: Publish Packages
      # this should only push changed ones:
      #  - unchanged: already in the registry
      #  - changed: already built and cached, so only will push
      # Skip s390x as emulation is unreliable
      run: |
        make OPTIONS="--skip-platforms linux/s390x" -C pkg push PUSHOPTIONS="--nobuild"

